### ISSUE TITLE
IOException During Execution

### ISSUE THREAD

**Issue by smiket** [jonstodle/DotnetVersion#3]
Hi there!  Nice job putting this together - looks like a nice tool to use in our dotnet core pipeline.  I ran into an issue and thought I'd log it here.  When trying to set a new version, I get an IOException as shown below.

I bounced machine, then left everything closed on reboot and just tried to use the tool as shown below (tried to make sure file was not actually in use).  Here is a stack trace:

C:\Dev\gitlab\nuget-packages\data-access>dotnet-version -p Directory.Build.props --new-version 1.0.12-alpha
Current version: 1.0.11-alpha
New version: 1.0.12-alpha

Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Dev\gitlab\nuget-packages\data-access\Directory.Build.props' because it is bein
g used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at DotnetVersion.Program.Run() in /home/runner/work/DotnetVersion/DotnetVersion/src/DotnetVersion/Program.cs:line 206
   at DotnetVersion.Program.OnExecute() in /home/runner/work/DotnetVersion/DotnetVersion/src/DotnetVersion/Program.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at DotnetVersion.Program.Main(String[] args) in /home/runner/work/DotnetVersion/DotnetVersion/src/DotnetVersion/Program.cs:line 17

**Comment by jonstodle** [comment]
Are you still able to reproduce this with version 1.5.0?

**Comment by jonstodle** [comment]
I'm closing this for now. Please comment should it still be a problem.
